// Export utilities for generating downloadable reports
// Supports CSV and formatted text exports

import type { StateData, AggregatedInsight } from "./mockApi";

interface ExportData {
  stateData: StateData[];
  insights: AggregatedInsight[];
  wastageCauses: { cause: string; percentage: number }[];
  generatedAt: string;
}

// Generate CSV content
export const generateCSV = (data: ExportData): string => {
  const lines: string[] = [];
  
  // Header
  lines.push("UrbanSave AI - Insights Report");
  lines.push(`Generated: ${new Date(data.generatedAt).toLocaleString()}`);
  lines.push("");
  
  // Aggregated Insights Section
  lines.push("=== AGGREGATED INSIGHTS BY ADMIN TYPE ===");
  lines.push("Admin Type,Average Savings (INR),Average Consumption (kWh),Top Wastage Cause,User Count");
  data.insights.forEach((insight) => {
    lines.push(
      `${insight.adminType},${insight.averageSavings},${insight.averageConsumption},${insight.topWastageCause},${insight.userCount}`
    );
  });
  lines.push("");
  
  // Wastage Causes Section
  lines.push("=== COMMON WASTAGE CAUSES ===");
  lines.push("Cause,Percentage");
  data.wastageCauses.forEach((cause) => {
    lines.push(`${cause.cause},${cause.percentage}%`);
  });
  lines.push("");
  
  // State Data Section
  lines.push("=== STATE-WISE ENERGY DATA ===");
  lines.push("State,State Code,Consumption (kWh),Potential Savings (INR),Intensity Level");
  data.stateData.forEach((state) => {
    lines.push(
      `${state.name},${state.code},${state.consumption},${state.savings},${state.intensity}`
    );
  });
  lines.push("");
  
  // Summary
  const totalConsumption = data.stateData.reduce((sum, s) => sum + s.consumption, 0);
  const totalSavings = data.stateData.reduce((sum, s) => sum + s.savings, 0);
  lines.push("=== SUMMARY ===");
  lines.push(`Total States Tracked,${data.stateData.length}`);
  lines.push(`Total Consumption (kWh),${totalConsumption.toLocaleString()}`);
  lines.push(`Total Potential Savings (INR),${totalSavings.toLocaleString()}`);
  lines.push(`Total Users,${data.insights.reduce((sum, i) => sum + i.userCount, 0)}`);
  
  return lines.join("\n");
};

// Generate and download CSV file
export const downloadCSV = (data: ExportData, filename: string = "UrbanSave_Insights_Report"): void => {
  const csvContent = generateCSV(data);
  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement("a");
  link.href = url;
  link.download = `${filename}_${new Date().toISOString().split("T")[0]}.csv`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

// Generate formatted text report
export const generateTextReport = (data: ExportData): string => {
  const separator = "═".repeat(60);
  const lines: string[] = [];
  
  lines.push(separator);
  lines.push("           URBANSAVE AI - INSIGHTS REPORT");
  lines.push(separator);
  lines.push(`Generated: ${new Date(data.generatedAt).toLocaleString()}`);
  lines.push("");
  
  // Key Metrics
  lines.push("📊 KEY METRICS");
  lines.push("─".repeat(40));
  data.insights.forEach((insight) => {
    lines.push(`\n${insight.adminType.toUpperCase()}`);
    lines.push(`  • Users: ${insight.userCount}`);
    lines.push(`  • Avg Savings: ₹${insight.averageSavings.toLocaleString()}`);
    lines.push(`  • Avg Consumption: ${insight.averageConsumption.toLocaleString()} kWh`);
    lines.push(`  • Top Issue: ${insight.topWastageCause}`);
  });
  
  lines.push("\n");
  lines.push("⚠️ TOP WASTAGE CAUSES");
  lines.push("─".repeat(40));
  data.wastageCauses.forEach((cause, index) => {
    const bar = "█".repeat(Math.floor(cause.percentage / 3));
    lines.push(`${index + 1}. ${cause.cause}`);
    lines.push(`   ${bar} ${cause.percentage}%`);
  });
  
  lines.push("\n");
  lines.push(separator);
  lines.push("         Report generated by UrbanSave AI");
  lines.push(separator);
  
  return lines.join("\n");
};

// Download text report
export const downloadTextReport = (data: ExportData, filename: string = "UrbanSave_Report"): void => {
  const content = generateTextReport(data);
  const blob = new Blob([content], { type: "text/plain;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement("a");
  link.href = url;
  link.download = `${filename}_${new Date().toISOString().split("T")[0]}.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

// Export as JSON (for data backup/transfer)
export const downloadJSON = (data: ExportData, filename: string = "UrbanSave_Data"): void => {
  const content = JSON.stringify(data, null, 2);
  const blob = new Blob([content], { type: "application/json;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement("a");
  link.href = url;
  link.download = `${filename}_${new Date().toISOString().split("T")[0]}.json`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};
